### ISSUE TITLE
Use case for signature

### ISSUE THREAD

**Issue by samjbmason** [soffes/download.personalsam.com#1]
I was just wondering what the signature check is for, are there any particular use cases where it helps out.

Sorry more of a q than an issue

**Comment by soffes** [comment]
No worries! Probably a little over board. Since the code is public, I wanted to add a little more security. This prevents people from making fake requests and spamming my Mixpanel analytics.

**Comment by samjbmason** [comment]
Ah right makes sense, so do you manually generate the signature param for every vid?

**Comment by soffes** [comment]
Nope. See this: https://github.com/soffes/personalsam.com/blob/master/app/models/episode.rb#L26

**Comment by samjbmason** [comment]
Ah ok thats great thanks
